In [ ]:
# 1- Use f-string para concaternar textos o valores numéricos. De 2 ejemplos.

In [10]:
marca = ("Toyota","kia")
año = 2022


In [12]:
print(f'Su auto marca {marca[1]} es del año: {año}')

Su auto marca kia es del año: 2022


In [17]:
raza = ("Pastor alemán", "Pitbull", "Doberman")
nombre = ("Bolita", "Blanca", "Frufru")
edad = ("3","2","3")

In [19]:
print(f'El perro de raza {raza[2]} , cuyo nombre es {nombre[2]} tiene {edad[2]} años')

El perro de raza Doberman , cuyo nombre es Frufru tiene 3 años


In [ ]:
#2- Crear una Lista de 3 distritos de Lima, añadir 2 distritos del Callao. Extraer el primer y último elemento usando el Indexing

In [52]:
dist_lima = ["Miraflores", "San Isidro", "San Borja"]

In [53]:
dist_lima.append('La Perla', 'Chucuito')

In [54]:
print(dist_lima)

['Ate', 'Lince', 'Los Olivos', ('La Perla', 'Chucuito')]


In [55]:
dist_lima[0]

'Ate'

In [56]:
dist_lima[-1]

('La Perla', 'Chucuito')

In [ ]:
#3- Crear un diccionario con los 5 distritos del ejercicio a. Incluir información de población proyectada e incidencia de pobreza (limite superior).Use la información del Mapa de Pobreza 2018

In [58]:
dic_dist = {'Miraflores':108855, 'San Isidro':67703 , 'San Borja':127102 , 'La Punta':3935, 'La Perla': 64454 }

In [61]:
dic_dist.update({'Miraflores':{'Pobl_prct':108855,'Pobr_inc':0.2}, 'San Isidro':{'Pobl_prct':67703,'Pobr_inc':0.1}, 'San Borja':{'Pobl_prct':127102,'Pobr_inc':0.7}, 'La Punta':{'Pobl_prct':3935,'Pobr_inc':3.7}, 'La Perla':{'Pobl_prct':64454,'Pobr_inc':4.7}})

In [71]:
dic_dist

{'Miraflores': {'Pobl_prct': 108855, 'Pobr_inc': 0.2},
 'San Isidro': {'Pobl_prct': 67703, 'Pobr_inc': 0.1},
 'San Borja': {'Pobl_prct': 127102, 'Pobr_inc': 0.7},
 'La Punta': {'Pobl_prct': 3935, 'Pobr_inc': 3.7},
 'La Perla': {'Pobl_prct': 64454, 'Pobr_inc': 4.7}}

In [90]:
Incidencia_pobreza_Miraflores = dic_dist.get('Miraflores').get('Pobr_inc')
Incidencia_pobreza_Miraflores

0.2

In [91]:
Incidencia_pobreza_SanIsidro = dic_dist.get('San Isidro').get('Pobr_inc')
Incidencia_pobreza_SanIsidro

0.1

In [92]:
Incidencia_pobreza_SanBorja = dic_dist.get('San Borja').get('Pobr_inc')
Incidencia_pobreza_SanBorja

0.7

In [93]:
Poblacion_Miraflores = dic_dist.get('Miraflores').get('Pobl_prct')
Poblacion_Miraflores

108855

In [94]:
Poblacion_SanIsidro = dic_dist.get('San Isidro').get('Pobl_prct')
Poblacion_SanIsidro

67703

In [95]:
Poblacion_SanBorja = dic_dist.get('San Borja').get('Pobl_prct')
Poblacion_SanBorja

127102

In [ ]:
#5- Crear matrices y dar dos ejemplos de concatenación. Unión vertical y horizontal.

In [150]:
import numpy as np
import pandas as pd

In [111]:
A = np.array([np.arange(0,10,2), np.arange(10,20,2), np.arange(20,30,2)])

In [112]:
B = np.array([np.arange(0,5), np.arange(10,15), np.arange(15,20)])

In [102]:
#Union horizontal
con1 = np.concatenate((A,B), axis = 1)
con1

array([[ 0,  2,  4,  6,  8,  0,  1,  2,  3,  4],
       [10, 12, 14, 16, 18, 10, 11, 12, 13, 14],
       [20, 22, 24, 26, 28, 15, 16, 17, 18, 19]])

In [103]:
#Union vertical
con2 = np.concatenate((A,B), axis = 0)
con2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# 6- Crear una matriz de dimensión 4x8, seleccionar las ultimas dos columnas y primeras 3 filas.

In [124]:
c = np.array([np.arange(0,8), np.arange(10,18), np.arange(20,28),np.arange(30,38)])

In [125]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15, 16, 17],
       [20, 21, 22, 23, 24, 25, 26, 27],
       [30, 31, 32, 33, 34, 35, 36, 37]])

In [126]:
np.shape(c)

(4, 8)

In [135]:
c[:,6:8]

array([[ 6,  7],
       [16, 17],
       [26, 27],
       [36, 37]])

In [131]:
c[0:3,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15, 16, 17],
       [20, 21, 22, 23, 24, 25, 26, 27]])

In [ ]:
#7- Obtener el estimador de la varianza del termino de perturbación

In [ ]:
# 𝐼−𝑋(𝑋′𝑋)−1𝑋

In [137]:
I = np.eye(8)
I

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [139]:
t = c.T
t

array([[ 0, 10, 20, 30],
       [ 1, 11, 21, 31],
       [ 2, 12, 22, 32],
       [ 3, 13, 23, 33],
       [ 4, 14, 24, 34],
       [ 5, 15, 25, 35],
       [ 6, 16, 26, 36],
       [ 7, 17, 27, 37]])

In [155]:
cinv = np.linalg.inv(c @ t)

LinAlgError: Singular matrix

In [156]:
print(np.linalg.det(c))

LinAlgError: Last 2 dimensions of the array must be square